import React from 'react';
import { AuthProvider, useAuth } from './context/AuthContext';
import { ToastProvider } from './components/ToastProvider';
import Navbar from './components/Navbar';
import Dashboard from './pages/Dashboard';

const AppContent = () => {
  const { isAuthenticated, loading } = useAuth();

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="spinner"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <Navbar />
      {isAuthenticated ? (
        <Dashboard />
      ) : (
        <div className="min-h-[calc(100vh-64px)] flex items-center justify-center px-4">
          <div className="text-center max-w-2xl">
            <div className="mb-8">
              <div className="w-32 h-32 bg-white rounded-full flex items-center justify-center mx-auto mb-5 shadow-2xl">
                <span className="text-8xl">⚡</span>
              </div>
              <h1 className="text-3xl md:text-5xl font-bold text-white mb-3 font-display leading-tight">
                Welcome to InterviewPreparation AI
              </h1>
              <p className="text-xl text-purple-100 mb-8">
                Ace your next interview with AI-powered practice questions tailored to your dream role
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-6 mb-2">
              <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
                <div className="text-4xl mb-3">🤖</div>
                <h3 className="text-white font-bold mb-2 font-display">AI-Powered</h3>
                <p className="text-purple-100 text-sm">
                  Get personalized questions generated by advanced AI
                </p>
              </div>

              <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
                <div className="text-4xl mb-3">📚</div>
                <h3 className="text-white font-bold mb-2 font-display">Learn & Practice</h3>
                <p className="text-purple-100 text-sm">
                  Deep dive into explanations and examples
                </p>
              </div>

              <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
                <div className="text-4xl mb-3">👥</div>
                <h3 className="text-white font-bold mb-2 font-display">Community Profiles</h3>
                <p className="text-purple-100 text-sm">
                  Explore job profiles created by other users
                </p>
              </div>
            </div>

            <p className="text-white text-lg">
              Please login or sign up to get started
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

function App() {
  return (
    <AuthProvider>
      <ToastProvider>
        <AppContent />
      </ToastProvider>
    </AuthProvider>
  );
}

export default App;
